import { selectorCreator } from "../base/selectorCreator";
const base = selectorCreator('debtors');
export const getDebtor = base('data');
export const getDebtorLoading = base('loading');
export const getDebtorError = base('error');
export const getDebtorComments = base('comments');
export const getDebtorActions = base('actions');
export const getDebtorId = base('data.id');
export const getPassportId = base('passport.id');
export const getPassport = base('passport');
