const type = require('./DBAddressConstructor');

module.exports = [
    new type("аллея", "ал"),
    new type("бульвар", "б-р"),
    new type("Взвоз", "взв"),
    new type("въезд", "взд"),
    new type("дорога", "дор"),
    new type("заезд", "ззд"),
    new type("километр", "км"),
    new type("кольцо", "к-цо"),
    new type("коса", "коса"),
    new type("линия", "лн"),
    new type("магистраль", "мгстр"),
    new type("набережная", "наб"),
    new type("переезд", "пер-д"),
    new type("переулок", "пер"),
    new type("площадка", "пл-ка"),
    new type("площадь", "пл."),
    new type("проезд", "пр-д"),
    new type("просек", "пр-к"),
    new type("просека", "пр-ка"),
    new type("проселок", "пр-лок"),
    new type("проспект", "пр-кт"),
    new type("проулок", "проул"),
    new type("разъезд", "рзд"),
    new type("ряд", "ряд"),
    new type("сквер", "с-р"),
    new type("спуск", "с-к"),
    new type("съезд", "сзд"),
    new type("тракт", "тракт"),
    new type("тупик", "туп"),
    new type("улица", "ул"),
    new type("шоссе", "ш")
]